---
# Variabili comuni a tutti gli host nell'inventario

app_project: "cloud1"
# Comando standard per Docker Compose V2
docker_compose_command: "docker compose"
# app_repo_url: "git@github.com:almat101/cloud-1.git"
app_repo_url: "https://github.com/almat101/cloud-1.git"
app_branch: "main"


# Nota: Le vars_files per i segreti (vars/secrets.yml) di solito si includono nel playbook principale
# o in un ruolo specifico (come app_config) a seconda di chi ha bisogno di quei segreti.