# [ec2_hosts]
# ec2_instance ansible_host=ec2-13-60-35-165.eu-north-1.compute.amazonaws.com ansible_user=ubuntu
# Explanation of fields:
# ec2_instance: arbitrary name for this machine, useful to reference it in playbooks
# ansible_host: public IP address or DNS name of your EC2 instance
# ansible_user: system user for SSH connection (e.g., 'ubuntu' for Ubuntu, 'ec2-user' for Amazon Linux)
# ansible_ssh_private_key_file: full path to the SSH key provided by AWS
### private key is configured in ansible.cfg, so no need to specify ansible_ssh_private_key_file here

# Development environment - Runs playbooks directly on the local machine
# with ansible_connection=local use local connection not SSH
### Usage: ansible-playbook  playbooks/deploy.yml --limit dev --ask-vault-pass --ask-become-pass
# when launching with localhost I also need sudo password(become_pass)


dev:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: ale

prod:
  hosts:
    ec2_instance:
      ansible_host: "{{ lookup('env', 'EC2_HOST') }}"
      ansible_user: amatta