# # roles/phpmyadmin/tasks/main.yml
---
- name: Ensure Docker Compose is available (sanity check)
  ansible.builtin.command: "{{ docker_compose_command }} version"
  register: docker_compose_version_check
  changed_when: false
  failed_when: docker_compose_version_check.rc != 0

- name: Stop and remove existing phpmyadmin service if running
  community.docker.docker_compose_v2:
    project_src: "{{ app_dest_path_compose }}"
    services: ["phpmyadmin"]
    state: absent # Arresta e rimuove i container e le reti
  ignore_errors: yes
  become: yes
  become_user: "{{ app_owner_user }}"

- name: Build the phpmyadmin service
  community.docker.docker_compose_v2:
    project_src: "{{ app_dest_path_compose }}"
    services: ["phpmyadmin"]
    build: always
  become: yes
  become_user: "{{ app_owner_user }}"

- name: Start the phpmyadmin service
  community.docker.docker_compose_v2:
    project_src: "{{ app_dest_path_compose }}"
    services: ["phpmyadmin"]
    state: present
  become: yes
  become_user: "{{ app_owner_user }}"
  register: phpmyadmin_start_result

- name: Wait for phpmyadmin to be healthy
  ansible.builtin.command: docker inspect --format='{{"{{"}}.State.Health.Status{{"}}"}}' phpmyadmin
  register: phpmyadmin_health
  retries: 10
  delay: 5
  until: phpmyadmin_health.stdout == 'healthy'
  
- name: Display phpmyadmin service status
  ansible.builtin.debug:
    msg: "Docker Compose services started. Status: {{ phpmyadmin_start_result }}"